server notls {
    bind 127.0.0.1 8083
    tls no
    workers 1
}

load ./opensync.so


# User routes
domain * {
    attach notls

    route /user/create {
        handler user_create_handler
    }

    route /upload {
        handler upload_handler
        methods post
        on_body_chunk body_chunk
    }
}

http_body_max 1073741824
http_body_disk_offload 0

http_body_chunk_size 65536